### ISSUE TITLE
Paragraph for address

### ISSUE THREAD

**Issue by TheBrockEllis** [pkrapf/RESUME#1]
It looks likes you have 2 paragraphs on the page: one for your name and one that has your entire address in it.

To get the address to be single spaced, I'd probably recommend putting each line into their own paragraph. You can wrap the entire address in a `div` element so you an adjust all of the margins all at once. i.e.

```html
<div id='address'>
  <p>Omaha, NE</p>
  <p> 402 555 5555</p>
  <p>email@address.com</p>
  <p> <a href='linkedin'>LinkedIn</a></p>
</div>
```

And in your CSS:
```css
/* We didn't talk about this kind of selector, but it selects all "p" elements that are children of the div with the id of "address" */
div#address p {
  margin-bottom: 0;
}
```

You can read a bit more about the `selector selector` here: (https://www.w3schools.com/cssref/sel_element_element.asp)[https://www.w3schools.com/cssref/sel_element_element.asp]
